
output_dir = 'workspace/pretrain/384_swintiny_segmentation_on_masked_autoencoder'
n_epochs = 200
visual_every_n_epochs = 20

[model_config]
class = 'core.models.segmentation.Training'
image_channels = 3
image_size = [384, 384]
n_classes = 3
class_names = ['backgound', 'pet', 'boarder']
backbone = 'swinv2_tiny'
pretrain_backbone_load_path = 'workspace/pretrain/384_swintiny_masked_autoencoder/ckp_net.pt'

learning_rate = 2e-4

[data_module_config]
training_batch_size = 8   # Reduce if OOM
test_batch_size = 8
n_training_loading_workers = 8
n_test_loading_workers = 8

[data_module_config.training_dataset_config]
class = 'core.datasets.oxford_iiit_pet.pet_segmentation.TrainingDataset'
data_root = 'datasets/oxford_iiit_pet'
load_size = [400, 400]
image_size = [384, 384]
preload = true
n_workers = 8

[data_module_config.test_dataset_config]
class = 'core.datasets.oxford_iiit_pet.pet_segmentation.TestDataset'
data_root = 'datasets/oxford_iiit_pet'
image_size = [384, 384]
preload = true
n_workers = 8

[data_module_config.visualization_dataset_config]
pool_size = 8