
output_dir = 'workspace/pretrain/256_convnexttiny_rotation_prediction'
n_epochs = 200

[model_config]
class = 'core.models.classification.Training'
image_channels = 3
image_size = [256, 256]
n_classes = 4
class_names = ['0deg', '90deg', '180deg', '270deg']
backbone = 'convnextv2_tiny'
learning_rate = 1e-4

[data_module_config]
training_batch_size = 8   # Reduce if OOM
test_batch_size = 8
n_training_loading_workers = 8
n_test_loading_workers = 8

[data_module_config.training_dataset_config]
class = 'core.datasets.oxford_iiit_pet.pet_image_rotation.TrainingDataset'
data_root = 'datasets/oxford_iiit_pet'
load_size = [300, 300]
image_size = [256, 256]
preload = true
n_workers = 8


[data_module_config.test_dataset_config]
class = 'core.datasets.oxford_iiit_pet.pet_image_rotation.TestDataset'
data_root = 'datasets/oxford_iiit_pet'
image_size = [256, 256]
preload = true
n_workers = 8