output_dir = 'workspace/train/256_convnexttiny_on_supervised_contrastive_learning_e100'
n_epochs = 100
visual_every_n_epochs = 10

use_lr_scheduler = true
min_learning_rate = 1e-6

[model_config]
class = 'core.models.pix2pix.Training'
image_channels = 3
image_size = [256, 256]
backbone = 'convnextv2_tiny'
pretrain_backbone_load_path = 'workspace/pretrain/256_convnexttiny_supervised_contrastive_learning_e100/ckp_net.pt'
learning_rate = 2e-4

[data_module_config]
training_batch_size = 8   # Reduce if OOM
test_batch_size = 8
n_training_loading_workers = 8
n_test_loading_workers = 8

[data_module_config.training_dataset_config]
class = 'core.datasets.oxford_iiit_pet.pet_decomposition.TrainingDataset'
data_root = 'datasets/oxford_iiit_pet'
mode = 'pet'
load_size = [300, 300]
image_size = [256, 256]
preload = true
n_workers = 8

[data_module_config.test_dataset_config]
class = 'core.datasets.oxford_iiit_pet.pet_decomposition.TestDataset'
data_root = 'datasets/oxford_iiit_pet'
mode = 'pet'
image_size = [256, 256]
preload = true
n_workers = 8

[data_module_config.visualization_dataset_config]
pool_size = 8