output_dir = 'workspace/train/384_swintiny_on_masked_autoencoder'
n_epochs = 100
visual_every_n_epochs = 10

use_lr_scheduler = true
min_learning_rate = 1e-6

[model_config]
class = 'core.models.pix2pix.Training'
image_channels = 3
image_size = [384, 384]
backbone = 'swinv2_tiny'
pretrain_backbone_load_path = 'workspace/pretrain/384_swintiny_masked_autoencoder/ckp_net.pt'
learning_rate = 2e-4

[data_module_config]
training_batch_size = 8   # Reduce if OOM
test_batch_size = 8
n_training_loading_workers = 8
n_test_loading_workers = 8


[data_module_config.training_dataset_config]
class = 'core.datasets.oxford_iiit_pet.pet_decomposition.TrainingDataset'
data_root = 'datasets/oxford_iiit_pet'
mode = 'pet'
load_size = [400, 400]
image_size = [384, 384]
preload = true
n_workers = 8

[data_module_config.test_dataset_config]
class = 'core.datasets.oxford_iiit_pet.pet_decomposition.TestDataset'
data_root = 'datasets/oxford_iiit_pet'
mode = 'pet'
image_size = [384, 384]
preload = true
n_workers = 8

[data_module_config.visualization_dataset_config]
pool_size = 8